# Copyright (c) 2026 Gianfranco Ceccolini
# SPDX-License-Identifier: MIT
#
# CE-2 Chorus — a Boss CE-2-inspired chorus effect for the MOD Online Builder.
#
# Mono in / mono out. Two controls: Rate and Depth. The plugin follows the
# original CE-2 topology — a single delayed voice with a sinusoidal LFO
# modulating a short delay line (~7 ms centre, ±3.5 ms swing), mixed 50/50
# with the dry signal. Linear interpolation across the fractional delay
# read position keeps pitch transitions smooth.
#
# This recipe is a cookbook example demonstrating a *time-based* effect:
# circular delay buffer, LFO state, fractional interpolation, activate()
# zeroing the buffer on (re)start. Compare with examples/gain.mk, which is
# a pure callback plugin with no state beyond two floats.
#
# Originally generated by Claude (Anthropic) from a one-line prompt, then
# validated end-to-end on a MOD Dwarf and contributed to the cookbook.

CE2_CHORUS_VERSION = 61d38eb638449647fb8395a35c5b8dab7e981ba7
CE2_CHORUS_SITE = https://github.com/DISTRHO/DPF.git
CE2_CHORUS_SITE_METHOD = git
CE2_CHORUS_BUNDLES = ce2-chorus.lv2

define CE2_CHORUS_PLUGIN_CPP
#include "DistrhoPlugin.hpp"
#include <cmath>
#include <cstring>

START_NAMESPACE_DISTRHO

// Max delay line length: 50 ms at 192 kHz gives plenty of headroom.
static const int kMaxDelaySamples = 9600;

class CE2ChorusPlugin : public Plugin
{
public:
    CE2ChorusPlugin()
        : Plugin(kParameterCount, 0, 0),
          fRate(0.5f),
          fDepth(0.4f),
          fPhase(0.0f),
          fWritePos(0),
          fSampleRate(44100.0f)
    {
        memset(fDelayLine, 0, sizeof(fDelayLine));
    }

protected:
    const char* getLabel()       const override { return "CE2Chorus"; }
    const char* getDescription() const override { return "Boss CE-2 inspired chorus effect."; }
    const char* getMaker()       const override { return "Gianfranco Ceccolini"; }
    const char* getHomePage()    const override { return "https://mod.audio"; }
    const char* getLicense()     const override { return "MIT"; }
    uint32_t    getVersion()     const override { return d_version(1, 0, 0); }
    int64_t     getUniqueId()    const override { return d_cconst('C', 'E', '2', 'c'); }

    void initParameter(uint32_t index, Parameter& parameter) override
    {
        switch (index)
        {
        case kRate:
            parameter.hints      = kParameterIsAutomatable;
            parameter.name       = "Rate";
            parameter.symbol     = "rate";
            parameter.unit       = "Hz";
            parameter.ranges.def = 0.5f;
            parameter.ranges.min = 0.1f;
            parameter.ranges.max = 5.0f;
            break;
        case kDepth:
            parameter.hints      = kParameterIsAutomatable;
            parameter.name       = "Depth";
            parameter.symbol     = "depth";
            parameter.unit       = "";
            parameter.ranges.def = 0.4f;
            parameter.ranges.min = 0.0f;
            parameter.ranges.max = 1.0f;
            break;
        default:
            break;
        }
    }

    float getParameterValue(uint32_t index) const override
    {
        switch (index)
        {
        case kRate:  return fRate;
        case kDepth: return fDepth;
        default:     return 0.0f;
        }
    }

    void setParameterValue(uint32_t index, float value) override
    {
        switch (index)
        {
        case kRate:  fRate  = value; break;
        case kDepth: fDepth = value; break;
        default: break;
        }
    }

    void activate() override
    {
        fSampleRate = (float)getSampleRate();
        fPhase      = 0.0f;
        fWritePos   = 0;
        memset(fDelayLine, 0, sizeof(fDelayLine));
    }

    void run(const float** inputs, float** outputs, uint32_t frames) override
    {
        const float* in  = inputs[0];
        float*       out = outputs[0];

        // CE-2 centre delay: ~7 ms, modulation swing: +-3.5 ms (depth-scaled)
        const float centreMs  = 7.0f;
        const float swingMs   = 3.5f * fDepth;
        const float centreSmp = centreMs  * fSampleRate * 0.001f;
        const float swingSmp  = swingMs   * fSampleRate * 0.001f;
        const float phaseInc  = fRate / fSampleRate;
        const float twoPi     = 6.283185307f;

        for (uint32_t i = 0; i < frames; ++i)
        {
            // Write current sample into delay line
            fDelayLine[fWritePos] = in[i];

            // LFO (sine)
            float lfo = sinf(fPhase * twoPi);
            fPhase += phaseInc;
            if (fPhase >= 1.0f) fPhase -= 1.0f;

            // Delay read position with fractional interpolation
            float delaySmp = centreSmp + lfo * swingSmp;
            if (delaySmp < 1.0f)   delaySmp = 1.0f;
            if (delaySmp > (float)(kMaxDelaySamples - 2))
                delaySmp = (float)(kMaxDelaySamples - 2);

            int   readInt  = fWritePos - (int)delaySmp;
            float frac     = delaySmp - (int)delaySmp;
            if (readInt < 0) readInt += kMaxDelaySamples;

            int readInt2 = readInt - 1;
            if (readInt2 < 0) readInt2 += kMaxDelaySamples;

            float delayed = fDelayLine[readInt] * (1.0f - frac)
                          + fDelayLine[readInt2] * frac;

            // Mix: 50% dry + 50% wet (classic CE-2 blend)
            out[i] = 0.5f * in[i] + 0.5f * delayed;

            fWritePos++;
            if (fWritePos >= kMaxDelaySamples) fWritePos = 0;
        }
    }

private:
    float fRate;
    float fDepth;
    float fPhase;
    float fDelayLine[kMaxDelaySamples];
    int   fWritePos;
    float fSampleRate;

    DISTRHO_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(CE2ChorusPlugin)
};

Plugin* createPlugin() { return new CE2ChorusPlugin(); }

END_NAMESPACE_DISTRHO
endef

define CE2_CHORUS_PLUGIN_INFO_H
#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND       "Gianfranco Ceccolini"
#define DISTRHO_PLUGIN_NAME        "CE-2 Chorus"
#define DISTRHO_PLUGIN_URI         "urn:mod-cookbook:ce2-chorus"

#define DISTRHO_PLUGIN_HAS_UI       0
#define DISTRHO_PLUGIN_IS_RT_SAFE   1
#define DISTRHO_PLUGIN_NUM_INPUTS   1
#define DISTRHO_PLUGIN_NUM_OUTPUTS  1

enum Parameters {
    kRate  = 0,
    kDepth = 1,
    kParameterCount
};

#endif
endef

define CE2_CHORUS_PLUGIN_MAKEFILE
#!/usr/bin/make -f
NAME = ce2-chorus
FILES_DSP = CE2ChorusPlugin.cpp
include ../../Makefile.plugins.mk
TARGETS = lv2_dsp
all: $$(TARGETS)
endef

define CE2_CHORUS_MANIFEST_TTL
@prefix lv2:  <http://lv2plug.in/ns/lv2core#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<urn:mod-cookbook:ce2-chorus>
    a lv2:Plugin , lv2:ModulatorPlugin ;
    lv2:binary <ce2-chorus_dsp.so> ;
    rdfs:seeAlso <ce2-chorus.ttl> .
endef

define CE2_CHORUS_PLUGIN_TTL
@prefix doap:  <http://usefulinc.com/ns/doap#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix lv2:   <http://lv2plug.in/ns/lv2core#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix units: <http://lv2plug.in/ns/extensions/units#> .

<urn:mod-cookbook:ce2-chorus>
    a lv2:Plugin , lv2:ModulatorPlugin ;
    doap:name "CE-2 Chorus" ;
    doap:license <http://opensource.org/licenses/MIT> ;
    doap:maintainer [
        foaf:name "Gianfranco Ceccolini" ;
        foaf:homepage <https://mod.audio>
    ] ;
    rdfs:comment "Boss CE-2 inspired chorus. Mono in / mono out. Rate and Depth controls." ;
    lv2:port [
        a lv2:InputPort , lv2:AudioPort ;
        lv2:index 0 ;
        lv2:symbol "in" ;
        lv2:name "Audio In"
    ] , [
        a lv2:OutputPort , lv2:AudioPort ;
        lv2:index 1 ;
        lv2:symbol "out" ;
        lv2:name "Audio Out"
    ] , [
        a lv2:InputPort , lv2:ControlPort ;
        lv2:index 2 ;
        lv2:symbol "rate" ;
        lv2:name "Rate" ;
        lv2:default 0.5 ;
        lv2:minimum 0.1 ;
        lv2:maximum 5.0 ;
        units:unit units:hz
    ] , [
        a lv2:InputPort , lv2:ControlPort ;
        lv2:index 3 ;
        lv2:symbol "depth" ;
        lv2:name "Depth" ;
        lv2:default 0.4 ;
        lv2:minimum 0.0 ;
        lv2:maximum 1.0
    ] .
endef

export CE2_CHORUS_PLUGIN_CPP
export CE2_CHORUS_PLUGIN_INFO_H
export CE2_CHORUS_PLUGIN_MAKEFILE
export CE2_CHORUS_MANIFEST_TTL
export CE2_CHORUS_PLUGIN_TTL

define CE2_CHORUS_CONFIGURE_CMDS
	mkdir -p $(@D)/examples/ce2-chorus
	printf '%s' "$$CE2_CHORUS_PLUGIN_CPP"      > $(@D)/examples/ce2-chorus/CE2ChorusPlugin.cpp
	printf '%s' "$$CE2_CHORUS_PLUGIN_INFO_H"   > $(@D)/examples/ce2-chorus/DistrhoPluginInfo.h
	printf '%s' "$$CE2_CHORUS_PLUGIN_MAKEFILE" > $(@D)/examples/ce2-chorus/Makefile
endef

define CE2_CHORUS_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(TARGET_CONFIGURE_OPTS) $(MAKE) NOOPT=true -C $(@D)/examples/ce2-chorus lv2_dsp
endef

define CE2_CHORUS_INSTALL_TARGET_CMDS
	mkdir -p $($(PKG)_PKGDIR)/ce2-chorus.lv2
	cp $(@D)/bin/ce2-chorus.lv2/ce2-chorus_dsp.so $($(PKG)_PKGDIR)/ce2-chorus.lv2/
	printf '%s' "$$CE2_CHORUS_MANIFEST_TTL" > $($(PKG)_PKGDIR)/ce2-chorus.lv2/manifest.ttl
	printf '%s' "$$CE2_CHORUS_PLUGIN_TTL"   > $($(PKG)_PKGDIR)/ce2-chorus.lv2/ce2-chorus.ttl
endef

$(eval $(generic-package))
